title: Personal website
author: Roman Rader
email: roman.rader@gmail.com
description: ""
baseurl: ""
url: "https://rrader.github.io/"
github_username:  rrader

theme: minima
plugins:
  - jekyll-feed

header_pages:
